### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sandlbn**

### CODE REVIEW

**Comment by zlatanvasovic** [comment]
Why are you always sending pull request? It's just the spam in commit
history.

2014-08-22 21:47 GMT+02:00 Marcin Spoczynski notifications@github.com:

> Merged #6 https://github.com/maridco/marid-vagrant/pull/6.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maridco/marid-vagrant/pull/6#event-156248760.

## 

Zlatan Vasović - _ZDroid_

**Comment by sandlbn** [comment]
You don't need to subscribe notifications from this repository :) but sorry ! Anyway, this is the last one.

**Comment by zlatanvasovic** [comment]
Notifications aren't problem. xd

2014-08-22 22:13 GMT+02:00 Marcin Spoczynski notifications@github.com:

> You don't need to subscribe notifications from this repository :) but
> sorry ! Anyway, this is the last one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maridco/marid-vagrant/pull/6#issuecomment-53114549.

## 

Zlatan Vasović - _ZDroid_

**Comment by mbmjertan** [comment]
Send pull requests for code changes (important ones), not readme edits ;)

**Comment by zlatanvasovic** [comment]
+1 MBM :P

2014-08-22 23:25 GMT+02:00 Mario Borna Mjertan notifications@github.com:

> Send pull requests for code changes (important ones), not readme edits ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maridco/marid-vagrant/pull/6#issuecomment-53122321.

## 

Zlatan Vasović - _ZDroid_

**Comment by sandlbn** [comment]
@iwebhub totally disagree, it all depends on the branch to which you want to push. So far there is only one master. I think that is better to 5 times improve, than do nothing. especially when you editing readme files on online editor, you don't have a choice, every edit create git patch .

**Comment by mbmjertan** [comment]
Yes, it is better to improve, but you have the right to push directly to the repository, so use it for readme files. Pull requests aren't needed for everything. Not every single readme change needs a pull request, push those directly, as you usually merge as soon as you send a request. Why do that?

Comments are available on commits as well, so that's not a problem.

**Pull request merged**
